
name: GoVulnCheck

on:
  workflow_call:

concurrency:
  group: govulncheck-${{ github.ref }}
  cancel-in-progress: true

jobs:
  govulncheck:
    runs-on: [self-hosted, Linux, X64, validator]
    container:
      image: us-docker.pkg.dev/palette-images/build-base-images/golang:1.23-alpine
    steps:
      - name: install-govulncheck
        run: GOBIN=/usr/local/bin go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: govulncheck-scan
        run: |
          go version
          govulncheck -mode source ./...
